### ISSUE TITLE
locales not connected to React components

### ISSUE THREAD

**Issue by kriscarle** [loggingroads/onboarding#63]
It looks like the strings in the React components are still hard-coded? Do you guys have a plan for how to wire this up.  It looks like this might be a good option: https://github.com/fnando/i18n-js

**Comment by simaob** [comment]
Yes this looks like a good option. Having a look now.

**Comment by simaob** [comment]
I believe I've connected most of them. This afternoon I'm gonna remove a bunch of files that we are not really using (some React Components that we stopped using in favour of Rails views).

**Comment by kriscarle** [comment]
Awesome, thanks! Was thinking of attempting it, but some of the Rails stuff is still new to me.
